### ISSUE TITLE
Overflow on division

### ISSUE THREAD

**Issue by treeowl** [NorfairKing/haskell-WAT#5]
Let me endorse the conclusion that we should wrap, so that

```haskell
minBound @Int `quotRem` (-1) == (minBound, 0)
```

**Comment by NorfairKing** [comment]
I'm sorry, I don't understand what you're suggesting. Would you like to propose an alternate implementation of a function in the Prelude?

**Comment by treeowl** [comment]
I have other priorities of my own, but I think you should propose getting rid of that error!
